version: '3'
services:
  #PHP Service
  php-app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/php
    volumes:
      - ./backend/:/var/www/html/php
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - php-app-network
    depends_on: 
      - mysql

  # Webserver 
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www/html/php
    ports:
      - "9000:80"
    volumes:
      - ./backend/:/var/www/html/php
      - ./docker/nginx/php/conf.d/:/etc/nginx/conf.d/
      - ./docker/log/php:/var/log/nginx/
    networks:
      - php-app-network
    depends_on: 
      - php-app

  # vue3
  vue-app:
    build:
      context: ./
      dockerfile: ./docker/Vue.Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/vue
    volumes:
      - ./frontend/:/var/www/html/vue
    ports:
      - "7000:8080"
    command: npm run serve
    networks:
      - vue-network

  # Webvueserver 
  webvueserver:
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /var/www/html/vue
    ports:
      - "7000:8080"
    volumes:
      - ./frontend/:/var/www/html/vue
      - ./docker/nginx/vue/conf.d/:/etc/nginx/conf.d/
      - ./docker/log/vue:/var/log/nginx/
    networks:
      - vue-network
    depends_on: 
      - vue-app

  #MySQL Service
  mysql:
    image: mysql:latest
    restart: unless-stopped
    hostname: dbdata
    ports:
      - "5306:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    env_file:
      - ./docker/env/.env_mysql
    networks:
      - php-app-network
#Docker Networks
networks:
  php-app-network:
    driver: bridge
  vue-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local

